version: "3.3"

services:
  django_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
    networks:
      - rev_proxy
      - db_net

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_net

volumes:
  db_data:

networks:
  rev_proxy:
    external:
      name: reverse_proxy_net

  db_net: